input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # Filtros opcionales para enriquecer los logs
  if [logger_name] == "com.udem.reservas.backend.controller.ReservaController" {
    mutate {
      add_field => { "log_type" => "controller" }
    }
  }
  
  if [level] == "ERROR" {
    mutate {
      add_tag => ["error_log"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "oasis-logs-%{+YYYY.MM.dd}"
  }
  
  # Opcional: Para debugging, puedes ver los logs en la consola de Logstash
  stdout {
    codec => rubydebug
  }
}